image:
  repository: ghcr.io/paperless-ngx/paperless-ngx
  pullPolicy: IfNotPresent
  tag: latest

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

paperlessConfig:
  additionalEnvs: []

paperlessNetwork:
  webPort: 8000
  sshPort: 30009
  certificateID: null
  rootURL: ""
  hostNetwork: false

# FIXME: Currently only user 1000 works.
# Any other uid is not mapped to the internal "git" user.
# https://github.com/go-gitea/gitea/issues/23632
paperlessRunAs:
  user: 1000
  group: 1000

paperlessStorage:
  data:
    type: ixVolume
    datasetName: data
  media:
    type: ixVolume
    datasetName: media
  export:
    type: ixVolume
    datasetName: export
  consume:
    type: ixVolume
    datasetName: config
  pgData:
    type: ixVolume
    datasetName: pgData
  pgBackup:
    type: ixVolume
    datasetName: pgBackup
